# Generated by Django 3.2.9 on 2021-12-07 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
