# Generated by Django 3.2.9 on 2021-12-07 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20211207_2104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
