# Generated by Django 3.2.9 on 2021-12-08 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='discount',
            new_name='amount',
        ),
    ]
